apiVersion: v1
kind: Secret
metadata:
  name: nanoleaf-secrets
type: Opaque
data:
  # Replace with base64 encoded values. Make sure there are no spaces or carriage returns!!
  Nanoleaf__IpAddress: ===
  Nanoleaf__AuthToken: ===
