version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "weekly"
    assignees:
      - "mitchfen"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: 'weekly'
    assignees:
      - "mitchfen"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: 'weekly'
    assignees:
      - "mitchfen"
