name: Publish image

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write
  checks: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-container:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker build -t ghcr.io/mitchfen/nanoleaf-controller:latest .
      - run: docker push ghcr.io/mitchfen/nanoleaf-controller:latest 

