name: Publish image

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write
  checks: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-container:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: ./buildContainerImage.ps1
        working-directory: src
        shell: pwsh
      - run: docker push ghcr.io/mitchfen/nanoleaf-controller:latest 
